const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
test('complete 5000-case UI run exports every comparison while yielding to the interface',async({page},info)=>{
  test.setTimeout(180000);await page.goto('./');await expect(page.locator('#solve')).toBeEnabled();await page.locator('.tool-launcher [data-view=demos]').click();await expect(page.locator('#demo-all')).toBeEnabled();
  await page.evaluate(()=>{window.peEndurance={ticks:0,long:[]};window.peEndurance.timer=setInterval(()=>peEndurance.ticks++,50);window.peEndurance.observer=new PerformanceObserver(list=>peEndurance.long.push(...list.getEntries().map(e=>e.duration)));peEndurance.observer.observe({entryTypes:['longtask']});});
  const before=Date.now();await page.locator('#demo-all').click();await expect(page.locator('#demo-stop')).toBeEnabled();await expect(page.locator('#demo-status')).toContainText('Completed: 5000 cases; 0 differ',{timeout:150000});await expect(page.locator('#demo-rows tr')).toHaveCount(25);
  const timing=await page.evaluate(()=>{clearInterval(peEndurance.timer);peEndurance.observer.disconnect();return{ticks:peEndurance.ticks,long_tasks_ms:peEndurance.long};});expect(timing.ticks).toBeGreaterThan(2);
  const pending=page.waitForEvent('download');await page.locator('#demo-export').click();const result=JSON.parse(await fs.readFile(await(await pending).path(),'utf8'));expect(result.tested).toBe(5000);expect(result.mismatches).toBe(0);expect(new Set(result.results.map(r=>r.index)).size).toBe(5000);expect(result.results.every(r=>r.matches)).toBe(true);
  await fs.writeFile(`test-results/demo-endurance-${info.project.name}.json`,JSON.stringify({cases:5000,mismatches:0,elapsed_ms:Date.now()-before,...timing,limitations:'This browser and host only; interval callbacks and long tasks do not prove displayed-frame smoothness.'},null,2));
});
test('maximum FFT uses bounded output rows and remains usable after a rejected request',async({page},info)=>{
  await page.goto('./');await expect(page.locator('#solve')).toBeEnabled();await page.locator('.tool-launcher [data-lab=signals]').click();await page.locator('#signal-x').fill(Array(4096).fill('1').join(','));await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#verification')).toContainText('Parseval');
  const bins=await page.evaluate(()=>JSON.parse(PEApp.state.result.visual).bins);expect(bins).toHaveLength(4096);expect(bins[0].value.real).toBeCloseTo(4096,6);expect(bins.slice(1).every(b=>Math.abs(b.value.real)+Math.abs(b.value.imag)<1e-8)).toBe(true);await expect(page.locator('#visual tbody tr')).toHaveCount(64);
  await page.locator('#signal-x').fill('1,NaN,3,4');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#verification')).toContainText('Input could not be solved');await page.locator('#signal-x').fill('1,0,0,0');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#verification')).toContainText('Parseval');await page.screenshot({path:`test-results/fft-result-${info.project.name}.png`,fullPage:true});
});
