const {test,expect}=require('@playwright/test');
async function ready(page){await page.goto('./');await expect(page.locator('#solve')).toBeEnabled();}
async function lab(page,name){await page.locator(`.tool-launcher [data-lab="${name}"]`).click();await expect(page.locator('#labs')).toBeVisible();}
async function statusOK(page){await expect(page.locator('#verification')).not.toContainText('Input could not be solved');}
test('guided matrix cells serialize and solve, with safe dimension changes',async({page})=>{
  await ready(page);await page.locator('#domain').selectOption('linear_algebra');await page.locator('#topic').selectOption('determinant');await page.locator('#guided-toggle').click();
  await page.getByRole('textbox',{name:'Matrix A row 1 column 1',exact:true}).fill('5');await page.getByRole('button',{name:'Use these values',exact:true}).click();await expect(page.locator('#input')).toHaveValue('5,2;3,4');await expect(page.locator('#auto-type')).not.toBeChecked();await page.locator('#solve').click();await expect(page.locator('#answer')).toContainText('14');
  await page.locator('#matrix-0-rows').selectOption('3');await expect(page.locator('#matrix-0-columns')).toHaveValue('3');await expect(page.locator('[data-matrix]')).toHaveCount(9);
});
test('clickable K-map supports six variables, X cells, Gray panels and a checked solution',async({page})=>{
  await ready(page);await page.locator('#domain').selectOption('logic');await page.locator('#topic').selectOption('kmap_minimization');await page.locator('#guided-toggle').click();await page.locator('#kmap-variables').selectOption('6');await expect(page.locator('.kmap-cell')).toHaveCount(64);await expect(page.locator('.kmap-panel')).toHaveCount(4);
  for(const index of [1,3,5,7]){await page.locator(`.kmap-cell[data-cell="${index}"]`).click();await expect(page.locator(`.kmap-cell[data-cell="${index}"]`)).toHaveAttribute('data-value','1');}
  await page.locator('.kmap-cell[data-cell="0"]').click();await expect(page.locator('.kmap-cell[data-cell="0"]')).toHaveAttribute('data-value','1');await page.locator('.kmap-cell[data-cell="0"]').click();await expect(page.locator('.kmap-cell[data-cell="0"]')).toHaveAttribute('data-value','X');
  await page.getByRole('button',{name:'Solve this map',exact:true}).click();await expect(page.locator('#verification')).toContainText('64 input assignments');await statusOK(page);
  await page.locator('#kmap-grouping').selectOption('manual');await page.locator('.kmap-cell[data-cell="0"]').click();await page.locator('.kmap-cell[data-cell="3"]').click();await page.getByRole('button',{name:'Add selected group',exact:true}).click();await expect(page.locator('#guided-status')).toContainText('do not form a Boolean cube');
});
test('circuit drawing solves AC, restores undo and produces PNG download',async({page})=>{
  await ready(page);await lab(page,'circuit');await expect(page.locator('#circuit-canvas')).toBeVisible();await page.getByRole('button',{name:'RC low-pass',exact:true}).click();await page.locator('#circuit-analysis').selectOption('ac');await page.locator('#circuit-frequency').fill(String(1/(2*Math.PI*.001)));await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#answer')).toContainText('Node voltages');await expect(page.locator('#verification')).toContainText('KCL');await statusOK(page);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save diagram PNG',exact:true}).click();expect((await download).suggestedFilename()).toMatch(/\.png$/);
  await page.getByRole('button',{name:'Clear drawing',exact:true}).click();await expect(page.locator('#circuit-netlist')).toHaveValue('');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('#circuit-netlist')).toHaveValue(/C C1/);
  await page.locator('#circuit-netlist').fill('D D1 a 0 0.7');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#verification')).toContainText('Input could not be solved');
});
test('signals operations run through the actual controls and reject invalid input',async({page})=>{
  await ready(page);await lab(page,'signals');await page.locator('#signal-x').fill('1,0,0,0');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#answer')).toContainText('4 complex samples');await expect(page.locator('#verification')).toContainText('Parseval');
  await page.locator('#signal-operation').selectOption('convolution');await page.locator('#signal-x').fill('1,2,3');await page.locator('#signal-h').fill('4,5');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#answer')).toContainText('4, 13, 22, 15');
  await page.locator('#signal-operation').selectOption('inverse_laplace');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#verification')).toContainText('forward-transform reconstruction');
  await page.locator('#signal-operation').selectOption('fft');await page.locator('#signal-x').fill('1,2,3');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#answer')).toContainText('power-of-two');
});
test('transition-table UI generates a state diagram, equations and 101 detector trace',async({page})=>{
  await ready(page);await lab(page,'fsm');await page.getByRole('button',{name:'Generate diagram & equations',exact:true}).click();await expect(page.locator('#answer')).toContainText('Simulation outputs: 0 0 1 0 1');await expect(page.locator('#visual canvas')).toHaveCount(1);await expect(page.locator('#visual')).toContainText('D-flip-flop input and output equations');await expect(page.locator('#verification')).toContainText('reachable-state equivalence');
  await statusOK(page);await expect(page.locator('#visual')).toContainText('G0');
});
test('preloaded demos work offline, compare stored answers, calibrate, page and cancel',async({page,context})=>{
  await ready(page);await expect(page.locator('body')).toHaveAttribute('data-offline-ready','true',{timeout:60000});await context.setOffline(true);await page.reload();await expect(page.locator('#solve')).toBeEnabled();await page.getByRole('button',{name:'Test demos · 825k cases',exact:true}).click();await expect(page.locator('#demo-rows tr')).toHaveCount(25);await expect(page.locator('#demo-status')).toContainText('5,000 easy cases ready');
  await page.locator('#demo-calibrate').click();await expect(page.locator('#demo-status')).toContainText('Completed: 25 cases; 0 differ');await expect(page.locator('#demo-timing')).toContainText('Measured estimate');await page.locator('#demo-next').click();await expect(page.locator('#demo-page')).toContainText('26–50');await page.locator('#demo-all').click();await expect(page.locator('#demo-stop')).toBeEnabled();await page.locator('#demo-stop').click();await expect(page.locator('#demo-status')).toContainText('Stopped safely');await expect(page.locator('#demo-export')).toBeEnabled();
  const download=page.waitForEvent('download');await page.locator('#demo-export').click();expect((await download).suggestedFilename()).toMatch(/demo-results\.json$/);
  await page.locator('#demo-domain').selectOption('logic');await expect(page.locator('#demo-run')).toBeEnabled();await page.locator('#demo-difficulty').selectOption('hard');await expect(page.locator('#demo-status')).toContainText('5,000 hard cases ready');await page.locator('#demo-run').click();await expect(page.locator('#demo-status')).toContainText('Completed: 25 cases; 0 differ');
});
test('every C++ signals form solves its preset and rejects a missing numeric field',async({page})=>{
  await ready(page);await lab(page,'signals');const options=await page.locator('#signal-operation option').evaluateAll(nodes=>nodes.map(n=>n.value));expect(options).toHaveLength(13);
  for(const operation of options){await page.locator('#signal-operation').selectOption(operation);await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#answer')).not.toHaveText('');await expect.poll(()=>page.evaluate(()=>PEApp.state.result?.topic)).toBe(({filter:'difference_equation',digital_response:'digital_frequency_response',z_transform:'finite_z_transform',inverse_z:'inverse_z_transform'})[operation]||operation);await statusOK(page);}
  await page.locator('#signal-operation').selectOption('generator');await page.locator('#signal-amplitude').fill('');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#lab-status')).toContainText('Enter a value for Amplitude');
});
test('network study controls solve equivalents, superposition, sensitivity and sweeps',async({page})=>{
  await ready(page);await lab(page,'circuit');await page.locator('#circuit-netlist').fill('V V1 in 0 12; R R1 in out 1000; R R2 out 0 2000');await page.locator('#circuit-study').selectOption('port');await page.locator('#circuit-port-positive').fill('out');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#answer')).toContainText('Thévenin voltage = 8');await statusOK(page);
  await page.locator('#circuit-study').selectOption('superposition');await page.locator('#circuit-observe').fill('out');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#answer')).toContainText('All-sources solve');await statusOK(page);
  await page.locator('#circuit-study').selectOption('sensitivity');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#answer')).toContainText('Local sensitivities');await statusOK(page);
  await page.locator('#circuit-study').selectOption('sweep');await expect(page.locator('#circuit-analysis')).toHaveValue('ac');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#answer')).toContainText('Largest sampled RMS magnitude');await statusOK(page);
});
test('lab switching retains edited signal and circuit input',async({page})=>{
  await ready(page);await lab(page,'signals');await page.locator('#signal-x').fill('7,8,9,10');await page.locator('.lab-tabs [data-lab="circuit"]').click();await page.locator('#circuit-netlist').fill('V V2 a 0 7; R R2 a 0 5');await page.locator('.lab-tabs [data-lab="signals"]').click();await expect(page.locator('#signal-x')).toHaveValue('7,8,9,10');await page.locator('.lab-tabs [data-lab="circuit"]').click();await expect(page.locator('#circuit-netlist')).toHaveValue('V V2 a 0 7; R R2 a 0 5');
});
test('guided values and keyboard K-map focus survive closing and reopening',async({page})=>{
  await ready(page);await page.locator('#domain').selectOption('linear_algebra');await page.locator('#topic').selectOption('determinant');await page.locator('#guided-toggle').click();await page.getByRole('textbox',{name:'Matrix A row 1 column 1',exact:true}).fill('17');await page.locator('#guided-toggle').click();await page.locator('#guided-toggle').click();await expect(page.getByRole('textbox',{name:'Matrix A row 1 column 1',exact:true})).toHaveValue('17');
  await page.locator('#domain').selectOption('logic');await page.locator('#topic').selectOption('kmap_minimization');const cell=page.locator('.kmap-cell[data-cell="0"]');await cell.focus();await page.keyboard.press('Space');await expect(cell).toBeFocused();await page.locator('#guided-toggle').click();await page.locator('#guided-toggle').click();await page.locator('#kmap-grouping').selectOption('manual');await page.getByRole('button',{name:'Solve this map',exact:true}).click();await expect(page.locator('#guided-status')).toContainText('Add manual groups');
});
test('update drafts restore edited signal fields, circuit text and manual map state',async({page})=>{
  await ready(page);await lab(page,'signals');await page.locator('#signal-operation').selectOption('convolution');await page.locator('#signal-x').fill('7,8,9');await page.locator('#signal-h').fill('2,3');await page.locator('.lab-tabs [data-lab="circuit"]').click();const net='V V9 a 0 42; R R9 a 0 100';await page.locator('#circuit-netlist').fill(net);await page.getByRole('button',{name:'RC low-pass',exact:true}).click();await expect(page.locator('#circuit-netlist')).toHaveValue(net);
  await page.evaluate(()=>dispatchEvent(new Event('pe-save-draft')));await page.reload();await expect(page.locator('#circuit-netlist')).toHaveValue(net);await page.locator('.lab-tabs [data-lab="signals"]').click();await expect(page.locator('#signal-operation')).toHaveValue('convolution');await expect(page.locator('#signal-x')).toHaveValue('7,8,9');await expect(page.locator('#signal-h')).toHaveValue('2,3');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#answer')).toContainText('14, 37, 42, 27');
});
test('new editors contain tables on narrow screens and keep labels separate',async({page},info)=>{
  test.setTimeout(120000);await ready(page);
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const name of ['circuit','signals','fsm']){await page.evaluate(name=>PELabs.openLab(name),name);await expect(page.locator('#lab-content h2')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();const overlaps=await page.locator('.field-grid').evaluateAll(grids=>grids.flatMap(g=>{const a=[...g.children].filter(n=>n.getClientRects().length).map(n=>n.getBoundingClientRect());return a.flatMap((x,i)=>a.slice(i+1).filter(y=>Math.min(x.right,y.right)>Math.max(x.left,y.left)+1&&Math.min(x.bottom,y.bottom)>Math.max(x.top,y.top)+1));}));expect(overlaps).toEqual([]);if(info.project.name==='desktop'&&[320,1440].includes(width))await page.screenshot({path:`test-results/lab-${name}-${width}.png`,fullPage:true});}}
});
test('manual K-map exports replay the same groups and blank circuit coordinates are rejected',async({page})=>{
  await ready(page);await page.locator('#domain').selectOption('logic');await page.locator('#topic').selectOption('kmap_minimization');await page.locator('#guided-toggle').click();await page.locator('#kmap-variables').selectOption('2');for(const index of [0,1]){await page.locator(`.kmap-cell[data-cell="${index}"]`).click();await expect(page.locator(`.kmap-cell[data-cell="${index}"]`)).toHaveAttribute('data-value','1');}await page.locator('#kmap-grouping').selectOption('manual');for(const index of [0,1])await page.locator(`.kmap-cell[data-cell="${index}"]`).click();await page.getByRole('button',{name:'Add selected group',exact:true}).click();await page.getByRole('button',{name:'Solve this map',exact:true}).click();await expect(page.locator('#result')).toBeVisible();const replay=await page.evaluate(async()=>({saved:PEApp.state.problem,answer:PEApp.state.result.answer.text,again:await PEApp.request('workbench',JSON.stringify(PEApp.state.problem))}));expect(replay.again.answer.text).toBe(replay.answer);expect(JSON.parse(replay.saved.input).groups).toEqual([[0,1]]);
  await page.locator('.tool-launcher [data-lab=circuit]').click();await page.locator('#circuit-x').fill('');await page.getByRole('button',{name:'Apply tool at coordinate',exact:true}).click();await expect(page.locator('#lab-status')).toContainText('Enter a finite value for Grid X');
});
