// Repeated maximum FFT rendering with an explicitly throttled browser renderer.
// The throttle is a test condition, not an emulation of a specific real phone.
const {chromium}=require('playwright');
const {expect}=require('@playwright/test');
const fs=require('node:fs/promises');
(async()=>{
 const output=process.argv[2];if(!output)throw Error('Provide a new evidence directory');await fs.mkdir(output);const browser=await chromium.launch({headless:true,executablePath:process.env.PE_BROWSER_PATH||undefined});
 try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PE_SITE_URL||'https://pocket-engineer.onrender.com/');await expect(page.locator('#solve')).toBeEnabled({timeout:60000});await expect(page.locator('body')).toHaveAttribute('data-offline-ready','true',{timeout:180000});await context.setOffline(true);
 const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await page.locator('.tool-launcher [data-lab=signals]').click();await page.locator('#signal-x').fill(Array(4096).fill('1').join(','));const button=page.getByRole('button',{name:'Calculate locally',exact:true});await button.click();await expect(page.locator('#verification')).toContainText('Parseval');await cdp.send('HeapProfiler.collectGarbage');const before=await cdp.send('Performance.getMetrics');const durations=[];
 for(let n=0;n<50;n++){const start=Date.now();await button.click();await expect(page.locator('#solve-form')).toHaveAttribute('aria-busy','false');await expect(page.locator('#verification')).toContainText('Parseval');const bins=await page.evaluate(()=>JSON.parse(PEApp.state.result.visual).bins);expect(bins[0].value.real).toBeCloseTo(4096,6);expect(bins.slice(1).every(b=>Math.abs(b.value.real)+Math.abs(b.value.imag)<1e-8)).toBe(true);await expect(page.locator('#visual tbody tr')).toHaveCount(64);durations.push(Date.now()-start);}
 await cdp.send('HeapProfiler.collectGarbage');const after=await cdp.send('Performance.getMetrics'),metric=(m,k)=>m.metrics.find(x=>x.name===k)?.value||0;const growth=metric(after,'JSHeapUsedSize')-metric(before,'JSHeapUsedSize');expect(growth).toBeLessThan(12000000);expect(errors).toEqual([]);durations.sort((a,b)=>a-b);const report={runs:50,samples_per_fft:4096,independent_expected:'constant sequence has DC=4096 and other bins=0',renderer_cpu_throttle:4,offline:true,dom_rows:64,heap_growth_bytes: growth,median_roundtrip_ms:durations[25],p95_roundtrip_ms:durations[47],page_errors:errors,limitations:'Host-specific stress envelope; renderer throttling does not reproduce all worker scheduling, GPU or physical-phone behavior. Roundtrip includes automation and rendering.'};await fs.writeFile(output+'/report.json',JSON.stringify(report,null,2));await page.screenshot({path:output+'/fft-stress.png',fullPage:true});console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
