// Inspect the installed diagnostic APK via its actual Android WebView/JNI.
const {_android}=require('playwright');
const {expect}=require('@playwright/test');
const fs=require('node:fs/promises');
const serial=process.env.PE_ANDROID_SERIAL;if(!/^emulator-\d+$/.test(serial||''))throw Error('Select a disposable emulator');
(async()=>{
 const output=process.argv[2];if(!output)throw Error('Provide a new evidence directory');await fs.mkdir(output);const device=(await _android.devices({omitDriverInstall:true})).find(d=>d.serial()===serial);if(!device)throw Error('Emulator unavailable');const report={serial,checks:[],limitations:'Actual debug APK and Android WebView/JNI in API35 emulator. Release instrumentation and frame measurement are separate.'};
 try{const page=await(await device.webView({pkg:'com.pocketengineer.app'})).page();page.setDefaultTimeout(30000);if(process.env.PE_ANDROID_LOCAL_ASSETS==='1'){for(const name of ['demos.js','demo-worker.js'])await page.route('**/assets/'+name,route=>route.fulfill({path:'www/'+name,contentType:'text/javascript'}));report.local_asset_experiment=true;await page.reload();}const shell=async command=>(await device.shell(command)).toString();await expect(page.locator('body')).toHaveAttribute('data-engine','android');await shell('svc wifi disable');await shell('svc data disable');
 async function tap(selector){await page.locator(selector).evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await shell('uiautomator dump /sdcard/pe-lab-test.xml');const xml=await shell('cat /sdcard/pe-lab-test.xml'),tag=xml.match(/<node\b[^>]*class="android.webkit.WebView"[^>]*>/)?.[0],bounds=tag?.match(/bounds="\[(\d+),(\d+)\]\[(\d+),(\d+)\]"/);if(!bounds)throw Error('WebView bounds unavailable');const r=await page.locator(selector).boundingBox(),scale=(Number(bounds[3])-Number(bounds[1]))/await page.evaluate(()=>innerWidth);await shell(`input tap ${Math.round(Number(bounds[1])+(r.x+r.width/2)*scale)} ${Math.round(Number(bounds[2])+(r.y+r.height/2)*scale)}`);}
 await tap('.nav[data-view=downloads]');await tap('#retry-cache');await expect(page.locator('body')).toHaveAttribute('data-offline-ready','true');report.checks.push('actual readiness button');await tap('.nav[data-view=workbench]');
 await page.locator('#domain').selectOption('logic');await page.locator('#topic').selectOption('kmap_minimization');await tap('#guided-toggle');await page.locator('#kmap-variables').selectOption('6');await expect(page.locator('.kmap-cell')).toHaveCount(64);await tap('.kmap-cell[data-cell="0"]');await expect(page.locator('.kmap-cell[data-cell="0"]')).toHaveAttribute('data-value','1');await page.getByRole('button',{name:'Solve this map',exact:true}).click();await expect(page.locator('#verification')).toContainText('64 input assignments');await device.screenshot({path:output+'/kmap.png'});report.checks.push('six-variable K-map native touch and solve');
 await tap('.tool-launcher [data-lab=circuit]');await page.getByRole('button',{name:'RC low-pass',exact:true}).click();await page.locator('#circuit-analysis').selectOption('ac');await page.getByRole('button',{name:'Solve this circuit',exact:true}).click();await expect(page.locator('#verification')).toContainText('KCL');await device.screenshot({path:output+'/circuit.png'});report.checks.push('AC drawn circuit through JNI');
 await page.getByRole('button',{name:'Save diagram PNG',exact:true}).first().evaluate(e=>e.id='pe-export-png');await tap('#pe-export-png');await expect.poll(()=>shell('dumpsys activity activities')).toMatch(/topResumedActivity[^\n]*documentsui/i);await device.screenshot({path:output+'/png-document-picker.png'});await shell('input keyevent 4');report.checks.push('native PNG document picker');
 await tap('.lab-tabs [data-lab=signals]');await page.locator('#signal-x').fill('1,0,0,0');await page.getByRole('button',{name:'Calculate locally',exact:true}).click();await expect(page.locator('#verification')).toContainText('Parseval');await device.screenshot({path:output+'/fft.png'});report.checks.push('FFT through JNI');
 await tap('.lab-tabs [data-lab=fsm]');await page.getByRole('button',{name:'Generate diagram & equations',exact:true}).click();await expect(page.locator('#answer')).toContainText('Simulation outputs: 0 0 1 0 1');await device.screenshot({path:output+'/state-machine.png'});report.checks.push('state-machine table and diagram');
 await tap('.nav[data-view=workbench]');await tap('.tool-launcher [data-view=demos]');await expect(page.locator('#demo-all')).toBeEnabled({timeout:60000});await tap('#demo-all');await expect(page.locator('#demo-status')).toContainText('Completed: 5000 cases; 0 differ',{timeout:180000});await device.screenshot({path:output+'/demo-5000.png'});report.checks.push('5000 stored demo comparisons with radios disabled');
 report.memory=await shell('dumpsys meminfo com.pocketengineer.app');report.success=true;console.log(JSON.stringify(report));
 }catch(e){await device.screenshot({path:output+'/failure.png'}).catch(()=>{});throw e;}finally{await fs.writeFile(output+'/report.json',JSON.stringify(report,null,2));await device.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
